stages:
  train:
    cmd: poetry run python -m src.train
    deps:
      - src/train.py
      - configs/schema.py
      - configs/validate.py
      - params.yaml
    outs:
      - models/model.pkl
    metrics:
      - metrics.json
