version: "3.8"

services:
  tracking:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_artifacts:/mlflow
    environment:
      - MLFLOW_BACKEND_URI=sqlite:///mlflow.db
